DROP SEQUENCE "SQ_MAE_PRESTAMO";
DROP SEQUENCE "SQ_DET_PRESTAMO";
DROP SEQUENCE "SQ_CFG_PARAMETRO";
DROP SEQUENCE "SQ_CFG_CONSTANTE";

DROP TABLE "DET_PRESTAMO";
DROP TABLE "MAE_PRESTAMO";
DROP TABLE "CFG_PARAMETRO";
DROP TABLE "CFG_CONSTANTE";

CREATE TABLE "CFG_CONSTANTE" (    
    "IDCONSTANTE" VARCHAR2(50) NOT NULL,
    "DSCCONSTANTE" VARCHAR2(200),
    "IDTIPODATO" VARCHAR2(30),
    "VALOR" VARCHAR2(2500), 
    "USUCREACION" VARCHAR2(50) DEFAULT user, 
    "FECCREACION" DATE DEFAULT SYSDATE, 
    "USUMODIF" VARCHAR2(50) DEFAULT user, 
    "FECMODIF" DATE DEFAULT SYSDATE,
     CONSTRAINT "PK_IDCONSTANTE" PRIMARY KEY ("IDCONSTANTE")
);

CREATE TABLE "CFG_PARAMETRO" (    
    "IDPAR" NUMBER(10) NOT NULL, 
    "IDTIPPAR" VARCHAR2(50) NOT NULL,
    "CODIGO" VARCHAR2(50), 
    "CODIGON" NUMBER(20,8),
    "CODIGOC" VARCHAR2(40), 
    "ABREVIATURA" VARCHAR2(100) NOT NULL, 
    "DESCRIPCION" VARCHAR2(1200) NOT NULL, 
    "DESCRIPCION2" VARCHAR2(400),
    "INDACTIVO" VARCHAR2(1) DEFAULT 'S', 
    "USUCREACION" VARCHAR2(50) DEFAULT user, 
    "FECCREACION" DATE DEFAULT SYSDATE, 
    "USUMODIF" VARCHAR2(50) DEFAULT user, 
    "FECMODIF" DATE DEFAULT SYSDATE,
     CONSTRAINT "PK_IDPAR" PRIMARY KEY ("IDPAR")
);

CREATE TABLE "MAE_PRESTAMO"
(
    "IDPRESTAMO" NUMBER(10) NOT NULL,
    "PRESTAMO" NUMBER(20,8) NOT NULL,
    "TASA" NUMBER(20,8) NOT NULL,
    "PLAZO" NUMBER(3) NOT NULL,
    "TIPOPLAZO" VARCHAR2(1) NOT NULL,
    "INDPERIODOGRACIA" VARCHAR2(1) NOT NULL,
    "FECDESEMBOLSO" DATE,
    "FECINIPRESTAMO" DATE,
    "FECFINPRESTAMO" DATE,
    "PERIODOGRACIA" NUMBER(2) NOT NULL,
    "INDCAPINTERES" VARCHAR2(1) NOT NULL,
    "EMAIL" VARCHAR2(1000),
    "ORIGENTRANS" VARCHAR2(10),
    "URL" VARCHAR2(150), 
    "USUCREACION" VARCHAR2(50) DEFAULT user, 
    "FECCREACION" DATE DEFAULT SYSDATE, 
    "USUMODIF" VARCHAR2(50) DEFAULT user, 
    "FECMODIF" DATE DEFAULT SYSDATE,
    CONSTRAINT "PK_IDPRESTAMO" PRIMARY KEY ("IDPRESTAMO")
);

CREATE TABLE "DET_PRESTAMO"
(
    "IDPRESTAMODET" NUMBER(10) NOT NULL,
    "IDPRESTAMO" NUMBER(10) NOT NULL,
    "PERIODO" NUMBER(3) NOT NULL,
    "CUOTA" NUMBER(20,8),
    "INTERES" NUMBER(20,8),
    "AMORTIZACION" NUMBER(20,8),
    "TOTALAMORTIZADO" NUMBER(20,8),
    "CAPITALPENDIENTE" NUMBER(20,8),
    "FECVENCPAGOCUOTA" DATE NOT null,
    "USUCREACION" VARCHAR2(50) DEFAULT user, 
    "FECCREACION" DATE DEFAULT SYSDATE, 
    "USUMODIF" VARCHAR2(50) DEFAULT user, 
    "FECMODIF" DATE DEFAULT SYSDATE,
    CONSTRAINT "PK_IDPRESTAMODET" PRIMARY KEY ("IDPRESTAMODET")
);

CREATE SEQUENCE "SQ_MAE_PRESTAMO"
 START WITH     1
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;

CREATE SEQUENCE "SQ_DET_PRESTAMO"
 START WITH     1
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;

CREATE SEQUENCE "SQ_CFG_PARAMETRO"
 START WITH     1
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;

CREATE SEQUENCE "SQ_CFG_CONSTANTE"
 START WITH     1
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;

insert into CFG_PARAMETRO (IDPAR,IDTIPPAR,CODIGO,CODIGON,CODIGOC,ABREVIATURA,DESCRIPCION,DESCRIPCION2,INDACTIVO,USUCREACION,FECCREACION,USUMODIF,FECMODIF)
       values (SQ_CFG_PARAMETRO.nextval, 'PAR_PRESTAMO', null, 1000, null,'MIN', 'Valor Minimo','Valor Minimo','S', 'RETO', SYSDATE, 'RETO', SYSDATE);
insert into CFG_PARAMETRO (IDPAR,IDTIPPAR,CODIGO,CODIGON,CODIGOC,ABREVIATURA,DESCRIPCION,DESCRIPCION2,INDACTIVO,USUCREACION,FECCREACION,USUMODIF,FECMODIF)
       values (SQ_CFG_PARAMETRO.nextval, 'PAR_PRESTAMO', null, 20000000, null,'MAX', 'Valor Minimo','Valor Minimo','S', 'RETO', SYSDATE, 'RETO', SYSDATE);

insert into CFG_PARAMETRO (IDPAR,IDTIPPAR,CODIGO,CODIGON,CODIGOC,ABREVIATURA,DESCRIPCION,DESCRIPCION2,INDACTIVO,USUCREACION,FECCREACION,USUMODIF,FECMODIF)
       values (SQ_CFG_PARAMETRO.nextval, 'PAR_TASA', null, 2, null,'MIN', 'Valor Minimo','Valor Minimo','S', 'RETO', SYSDATE, 'RETO', SYSDATE);
insert into CFG_PARAMETRO (IDPAR,IDTIPPAR,CODIGO,CODIGON,CODIGOC,ABREVIATURA,DESCRIPCION,DESCRIPCION2,INDACTIVO,USUCREACION,FECCREACION,USUMODIF,FECMODIF)
       values (SQ_CFG_PARAMETRO.nextval, 'PAR_TASA', null, 20, null,'MAX', 'Valor Minimo','Valor Minimo','S', 'RETO', SYSDATE, 'RETO', SYSDATE);

insert into CFG_PARAMETRO (IDPAR,IDTIPPAR,CODIGO,CODIGON,CODIGOC,ABREVIATURA,DESCRIPCION,DESCRIPCION2,INDACTIVO,USUCREACION,FECCREACION,USUMODIF,FECMODIF)
       values (SQ_CFG_PARAMETRO.nextval, 'PAR_PERIODO', null, 2, null,'MIN', 'Valor Minimo','Valor Minimo','S', 'RETO', SYSDATE, 'RETO', SYSDATE);
insert into CFG_PARAMETRO (IDPAR,IDTIPPAR,CODIGO,CODIGON,CODIGOC,ABREVIATURA,DESCRIPCION,DESCRIPCION2,INDACTIVO,USUCREACION,FECCREACION,USUMODIF,FECMODIF)
       values (SQ_CFG_PARAMETRO.nextval, 'PAR_PERIODO', null, 10, null,'MAX', 'Valor Minimo','Valor Minimo','S', 'RETO', SYSDATE, 'RETO', SYSDATE);

insert into CFG_PARAMETRO (IDPAR,IDTIPPAR,CODIGO,CODIGON,CODIGOC,ABREVIATURA,DESCRIPCION,DESCRIPCION2,INDACTIVO,USUCREACION,FECCREACION,USUMODIF,FECMODIF)
       values (SQ_CFG_PARAMETRO.nextval, 'PAR_PERIODOGRACIA', null, 2, null,'MIN', 'Valor Minimo','Valor Minimo','S', 'RETO', SYSDATE, 'RETO', SYSDATE);
insert into CFG_PARAMETRO (IDPAR,IDTIPPAR,CODIGO,CODIGON,CODIGOC,ABREVIATURA,DESCRIPCION,DESCRIPCION2,INDACTIVO,USUCREACION,FECCREACION,USUMODIF,FECMODIF)
       values (SQ_CFG_PARAMETRO.nextval, 'PAR_PERIODOGRACIA', null, 10, null,'MAX', 'Valor Minimo','Valor Minimo','S', 'RETO', SYSDATE, 'RETO', SYSDATE);

​